import { codexSkillAdapter } from "./codexSkillAdapter";
import type { Adapter, AdapterOutput, EffectiveContext, EffectiveContextBlock } from "./types";

const instructionsFileName = "AGENTS.md";

export const codexAdapter: Adapter = {
  async build(input): Promise<AdapterOutput> {
    const skillAdapterOutput = codexSkillAdapter.build(input);
    const warnings = input.effectiveContext.skills.flatMap((skill) => skill.warnings);

    const contents = [
      "# AGENTS",
      "This file is generated by AIE OS. Do not edit directly.",
      renderPersona(input.effectiveContext),
      renderCriticalRules(input.effectiveContext.criticalRules),
      renderSections(input.effectiveContext.sections),
      skillAdapterOutput.markdown,
    ]
      .filter((part) => part !== "")
      .join("\n\n")
      .concat("\n");

    return {
      bootstrapPrompt: renderBootstrapPrompt(instructionsFileName),
      files: [
        {
          contents,
          path: instructionsFileName,
        },
      ],
      primaryArtifact: instructionsFileName,
      skillAdapterOutput,
      warnings,
    };
  },
  tool: "codex",
};

function renderBootstrapPrompt(instructionsFileName: string): string {
  return [
    "Before doing any task work in this repository, load and follow the generated repository instructions.",
    `Read \`${instructionsFileName}\` at the repo root and treat it as the authoritative instruction set for this repo for the rest of the session.`,
    "If a task conflicts with those instructions, state the conflict and follow the higher-priority rule.",
    `If context is summarized, compacted, or partially lost, reload \`${instructionsFileName}\` from disk before continuing instead of relying on memory.`,
    "After loading the instructions, continue with the user’s task without restating the full file unless asked.",
    "",
    "",
  ].join("\n");
}

function renderPersona(effectiveContext: EffectiveContext): string {
  return ["## Persona", "", effectiveContext.persona.content].join("\n");
}

function renderCriticalRules(blocks: EffectiveContextBlock[]): string {
  if (blocks.length === 0) {
    return "";
  }

  const groups = groupBlocksBySectionLabel(blocks);
  const parts = ["## Critical Rules"];

  for (const group of groups) {
    parts.push("", `### ${group.sectionLabel}`);

    for (const block of group.blocks) {
      parts.push("", block.content);
    }
  }

  return parts.join("\n");
}

function renderSections(blocks: EffectiveContextBlock[]): string {
  if (blocks.length === 0) {
    return "";
  }

  const groups = groupBlocksBySectionLabel(blocks);
  const renderedGroups: string[] = [];

  for (const group of groups) {
    const parts = [`## ${group.sectionLabel}`];

    for (const block of group.blocks) {
      parts.push("", block.content);
    }

    renderedGroups.push(parts.join("\n"));
  }

  return renderedGroups.join("\n\n");
}

function groupBlocksBySectionLabel(
  blocks: EffectiveContextBlock[],
): Array<{ blocks: EffectiveContextBlock[]; sectionLabel: string }> {
  const groups: Array<{ blocks: EffectiveContextBlock[]; sectionLabel: string }> = [];
  const seen = new Map<string, { blocks: EffectiveContextBlock[]; sectionLabel: string }>();

  for (const block of blocks) {
    const existing = seen.get(block.sectionLabel);

    if (existing) {
      existing.blocks.push(block);
      continue;
    }

    const group = {
      blocks: [block],
      sectionLabel: block.sectionLabel,
    };

    seen.set(block.sectionLabel, group);
    groups.push(group);
  }

  return groups;
}
