import { codexSkillAdapter } from "./codexSkillAdapter";
import type { Adapter, AdapterOutput, EffectiveContext, EffectiveContextSection } from "./types";

export const codexAdapter: Adapter = {
  async build(input): Promise<AdapterOutput> {
    const skillAdapterOutput = codexSkillAdapter.build(input);
    const warnings = input.effectiveContext.skills.flatMap((skill) => skill.warnings);
    const criticalRules = renderCriticalRules(input.effectiveContext.sections);
    const workingProfile = renderWorkingProfile(input.effectiveContext);
    const agentBehavior = renderSectionGroup(
      "Agent Behavior",
      input.effectiveContext.sections.filter(
        (section) =>
          section.layer === "Universal Agent Rules" || section.layer === "Persona",
      ),
    );
    const projectRules = renderSectionGroup(
      "Project Rules",
      input.effectiveContext.sections.filter(
        (section) => section.layer === "Project Coding Standards",
      ),
    );
    const sharedRules = renderSectionGroup(
      "Shared Rules",
      input.effectiveContext.sections.filter(
        (section) =>
          section.layer !== "Universal Agent Rules" &&
          section.layer !== "Persona" &&
          section.layer !== "Project Coding Standards",
      ),
    );

    const contents = [
      "# AGENTS",
      "This file is generated by AIE OS. Do not edit directly.",
      criticalRules,
      workingProfile,
      agentBehavior,
      projectRules,
      sharedRules,
      skillAdapterOutput.markdown,
    ]
      .filter((part) => part !== "")
      .join("\n\n")
      .concat("\n");

    return {
      files: [
        {
          contents,
          path: "AGENTS.md",
        },
      ],
      primaryArtifact: "AGENTS.md",
      skillAdapterOutput,
      warnings,
    };
  },
  tool: "codex",
};

function renderCriticalRules(sections: EffectiveContextSection[]): string {
  const renderedSections = sections
    .filter((section) => section.parsed.criticalRules.length > 0)
    .map((section) =>
      [
        `### ${section.layer}: ${section.heading}`,
        "",
        ...section.parsed.criticalRules,
      ].join("\n"),
    );

  if (renderedSections.length === 0) {
    return "";
  }

  return ["## Critical Rules", ...renderedSections].join("\n\n");
}

function renderWorkingProfile(effectiveContext: EffectiveContext): string {
  const selection = effectiveContext.manifest.selection;

  return [
    "## Working Profile",
    "",
    `- Persona: ${selection.persona}`,
    `- Languages: ${formatList(selection.languages)}`,
    `- Application types: ${formatList(selection.applicationTypes)}`,
    `- Frameworks: ${formatList(selection.frameworks)}`,
  ].join("\n");
}

function renderSectionGroup(title: string, sections: EffectiveContextSection[]): string {
  const renderedSections = sections
    .map(renderParsedSection)
    .filter((section) => section !== "");

  if (renderedSections.length === 0) {
    return "";
  }

  return [`## ${title}`, ...renderedSections].join("\n\n");
}

function renderParsedSection(section: EffectiveContextSection): string {
  const rules = [...section.parsed.rules, ...section.parsed.unclassified];
  const preferredPatterns = section.parsed.preferredPatterns;
  const forbiddenPatterns = section.parsed.forbiddenPatterns;

  if (
    rules.length === 0 &&
    preferredPatterns.length === 0 &&
    forbiddenPatterns.length === 0
  ) {
    return "";
  }

  const parts = [`### ${section.layer}: ${section.heading}`];

  if (rules.length > 0) {
    parts.push("", ...rules);
  }

  if (preferredPatterns.length > 0) {
    parts.push("", "#### Preferred Patterns", "", ...preferredPatterns);
  }

  if (forbiddenPatterns.length > 0) {
    parts.push("", "#### Forbidden Patterns", "", ...forbiddenPatterns);
  }

  return parts.join("\n");
}

function formatList(items: string[]): string {
  if (items.length === 0) {
    return "none";
  }

  return items.join(", ");
}
